from pathlib import Path

# app-auth: build user box with DOM/textContent instead of interpolating display name into innerHTML.
p=Path('public/js/app-auth.js'); s=p.read_text()
old='''          const box=document.createElement("div");\n          box.id="minyaUserBox"; box.className="minya-user-box";\n          box.innerHTML=`<span>${d.user.display_name}</span><small>${d.user.role==="admin"?"مدير":d.user.role==="editor"?"محرر":"قراءة فقط"}</small><button type="button" id="minyaLogoutBtn">خروج</button>`;\n          header.appendChild(box);\n          document.getElementById("minyaLogoutBtn").onclick=async()=>{ await fetch("/api/auth/logout",{method:"POST"}); location.replace("/login.html"); };'''
new='''          const box=document.createElement("div");\n          box.id="minyaUserBox"; box.className="minya-user-box";\n          const name=document.createElement("span");\n          name.textContent=d.user.display_name || d.user.username || "مستخدم";\n          const role=document.createElement("small");\n          role.textContent=d.user.role==="admin"?"مدير":d.user.role==="editor"?"محرر":"قراءة فقط";\n          const logout=document.createElement("button");\n          logout.type="button"; logout.id="minyaLogoutBtn"; logout.textContent="خروج";\n          box.append(name,role,logout); header.appendChild(box);\n          logout.onclick=async()=>{ await fetch("/api/auth/logout",{method:"POST"}); location.replace("/login.html"); };'''
assert old in s, 'auth user box not found'; s=s.replace(old,new,1); p.write_text(s)

# app-admin-security: remove implicit id globals.
p=Path('public/js/app-admin-security.js'); s=p.read_text()
old="""    build(); const ub=document.getElementById('securityUsersBody'), sb=document.getElementById('securitySessionsBody'); if(!ub||!sb)return;"""
new="""    build(); const ub=document.getElementById('securityUsersBody'), sb=document.getElementById('securitySessionsBody');\n    const sessionsCount=document.getElementById('secSessions'), usersCount=document.getElementById('secUsers'), lastLogin=document.getElementById('secLastLogin'), lastFailed=document.getElementById('secLastFailed'), msg=document.getElementById('securityMsg');\n    if(!ub||!sb||!sessionsCount||!usersCount||!lastLogin||!lastFailed||!msg)return;"""
assert old in s; s=s.replace(old,new,1)
s=s.replace("secSessions.textContent=sessions.length; secUsers.textContent=users.filter(x=>x.is_active).length;","sessionsCount.textContent=sessions.length; usersCount.textContent=users.filter(x=>x.is_active).length;",1)
s=s.replace("secLastLogin.textContent=dt(last); secLastFailed.textContent=dt(failed);","lastLogin.textContent=dt(last); lastFailed.textContent=dt(failed);",1)
s=s.replace("securityMsg.textContent='تم إنهاء الجلسات'","msg.textContent='تم إنهاء الجلسات'")
s=s.replace("securityMsg.textContent=e.message","msg.textContent=e.message")
old="""document.getElementById('securityCleanup')?.addEventListener('click',async()=>{try{const d=await api('/api/security/cleanup',{method:'POST'});securityMsg.textContent=`تم حذف ${d.sessions_removed||0} جلسة منتهية و${d.attempts_removed||0} محاولة قديمة`;load();}catch(e){securityMsg.textContent=e.message;}});"""
new="""document.getElementById('securityCleanup')?.addEventListener('click',async()=>{const msg=document.getElementById('securityMsg');try{const d=await api('/api/security/cleanup',{method:'POST'});if(msg)msg.textContent=`تم حذف ${d.sessions_removed||0} جلسة منتهية و${d.attempts_removed||0} محاولة قديمة`;load();}catch(e){if(msg)msg.textContent=e.message;}});"""
assert old in s; s=s.replace(old,new,1); p.write_text(s)

# app-admin-users: make edit form references explicit.
p=Path('public/js/app-admin-users.js'); s=p.read_text()
insert="""  function editEls(){ return {\n    id:document.getElementById('editUserId'), title:document.getElementById('editUserTitle'), display:document.getElementById('editDisplayName'), role:document.getElementById('editRole'), active:document.getElementById('editActive'), password:document.getElementById('editPassword'), dialog:document.getElementById('userEditDialog'), logout:document.getElementById('logoutUserEverywhere'), msg:document.getElementById('usersManageMsg'), save:document.getElementById('saveUserEdit')\n  }; }\n"""
needle="  function openEdit(user){\n"
assert needle in s; s=s.replace(needle,insert+needle,1)
old="""  function openEdit(user){\n    editUserId.value=user.id; editUserTitle.textContent=`${user.display_name} (${user.username})`;\n    editDisplayName.value=user.display_name||''; editRole.value=user.role; editActive.value=String(Number(Boolean(user.is_active))); editPassword.value='';\n    userEditDialog.classList.remove('hidden');\n    const self=Number(user.id)===Number(currentUser?.id);\n    editActive.disabled=self;\n    logoutUserEverywhere.disabled=Number(user.active_sessions||0)===0;\n    usersManageMsg.textContent=self?'هذا هو حسابك الحالي؛ لا يمكن إيقافه من هذه الجلسة.':'';\n    userEditDialog.scrollIntoView({behavior:'smooth',block:'nearest'});\n  }"""
new="""  function openEdit(user){\n    const e=editEls(); if(!e.id||!e.title||!e.display||!e.role||!e.active||!e.password||!e.dialog||!e.logout||!e.msg)return;\n    e.id.value=user.id; e.title.textContent=`${user.display_name} (${user.username})`;\n    e.display.value=user.display_name||''; e.role.value=user.role; e.active.value=String(Number(Boolean(user.is_active))); e.password.value='';\n    e.dialog.classList.remove('hidden');\n    const self=Number(user.id)===Number(currentUser?.id); e.active.disabled=self; e.logout.disabled=Number(user.active_sessions||0)===0;\n    e.msg.textContent=self?'هذا هو حسابك الحالي؛ لا يمكن إيقافه من هذه الجلسة.':''; e.dialog.scrollIntoView({behavior:'smooth',block:'nearest'});\n  }"""
assert old in s; s=s.replace(old,new,1)
old="""  async function save(){\n    const id=Number(editUserId.value); if(!id)return;\n    const payload={display_name:editDisplayName.value.trim(),role:editRole.value,is_active:Number(editActive.value)};\n    if(editPassword.value) payload.password=editPassword.value;\n    if(payload.password&&payload.password.length<8){usersManageMsg.textContent='كلمة المرور يجب أن تكون 8 أحرف على الأقل.';return;}\n    const sensitive=payload.role==='admin'||payload.is_active===0||Boolean(payload.password);\n    if(sensitive&&!confirm('هذا تغيير حساس على حساب المستخدم. هل تريد المتابعة؟'))return;\n    saveUserEdit.disabled=true; usersManageMsg.textContent='جاري حفظ التعديلات...';\n    try{\n      const d=await api(`/api/users/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});\n      usersManageMsg.textContent=d.message||'تم تحديث المستخدم'; editPassword.value=''; await load(); userEditDialog.classList.add('hidden');\n    }catch(e){usersManageMsg.textContent=e.message;}finally{saveUserEdit.disabled=false;}\n  }"""
new="""  async function save(){\n    const e=editEls(); if(!e.id||!e.display||!e.role||!e.active||!e.password||!e.msg||!e.save||!e.dialog)return;\n    const id=Number(e.id.value); if(!id)return;\n    const payload={display_name:e.display.value.trim(),role:e.role.value,is_active:Number(e.active.value)}; if(e.password.value) payload.password=e.password.value;\n    if(payload.password&&payload.password.length<8){e.msg.textContent='كلمة المرور يجب أن تكون 8 أحرف على الأقل.';return;}\n    const sensitive=payload.role==='admin'||payload.is_active===0||Boolean(payload.password); if(sensitive&&!confirm('هذا تغيير حساس على حساب المستخدم. هل تريد المتابعة؟'))return;\n    e.save.disabled=true; e.msg.textContent='جاري حفظ التعديلات...';\n    try{const d=await api(`/api/users/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});e.msg.textContent=d.message||'تم تحديث المستخدم';e.password.value='';await load();e.dialog.classList.add('hidden');}\n    catch(err){e.msg.textContent=err.message;}finally{e.save.disabled=false;}\n  }"""
assert old in s; s=s.replace(old,new,1)
old="""  async function logoutAll(){\n    const id=Number(editUserId.value); if(!id)return;"""
new="""  async function logoutAll(){\n    const e=editEls(); if(!e.id||!e.msg||!e.dialog)return; const id=Number(e.id.value); if(!id)return;"""
assert old in s; s=s.replace(old,new,1)
s=s.replace("usersManageMsg.textContent=`تم إنهاء ${d.count||0} جلسة`","e.msg.textContent=`تم إنهاء ${d.count||0} جلسة`",1)
s=s.replace("userEditDialog.classList.add('hidden')","e.dialog.classList.add('hidden')",1)
s=s.replace("usersManageMsg.textContent=e.message","e.msg.textContent=e.message",1)
# explicit close handler
s=s.replace("document.getElementById('closeUserEdit')?.addEventListener('click',()=>userEditDialog.classList.add('hidden'))","document.getElementById('closeUserEdit')?.addEventListener('click',()=>document.getElementById('userEditDialog')?.classList.add('hidden'))",1)
p.write_text(s)
