from pathlib import Path
p=Path('server.js')
s=p.read_text()

# Add login attempt table after sessions table block if not already present.
anchor='''  CREATE TABLE IF NOT EXISTS audit_logs (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,'''
insert='''  CREATE TABLE IF NOT EXISTS login_attempts (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    username TEXT NOT NULL,\n    success INTEGER NOT NULL DEFAULT 0,\n    ip_address TEXT DEFAULT '',\n    created_at TEXT DEFAULT CURRENT_TIMESTAMP\n  );\n  CREATE INDEX IF NOT EXISTS idx_login_attempts_user_time ON login_attempts(username, created_at);\n  CREATE TABLE IF NOT EXISTS audit_logs (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,'''
if 'CREATE TABLE IF NOT EXISTS login_attempts' not in s:
    assert anchor in s, 'audit table anchor not found'
    s=s.replace(anchor,insert,1)

# Replace login endpoint with lockout-aware version.
start=s.index('app.post("/api/auth/login", (req, res) => {')
end=s.index('app.post("/api/auth/logout"', start)
new_login='''app.post("/api/auth/login", (req, res) => {\n  const { username, password } = req.body;\n  const normalized=String(username || "").trim();\n  const ip=String(req.headers["x-forwarded-for"] || req.socket?.remoteAddress || "").split(",")[0].trim().slice(0,120);\n  const windowStart=new Date(Date.now()-15*60*1000).toISOString();\n  const failed=db.prepare(`SELECT COUNT(*) AS c FROM login_attempts WHERE username=? AND success=0 AND created_at>=?`).get(normalized,windowStart).c;\n  if(failed>=5){\n    audit(null,"LOGIN_LOCKED","user",normalized,`Too many failed attempts from ${ip}`);\n    return res.status(429).json({ok:false,message:"تم إيقاف محاولات الدخول مؤقتًا لمدة 15 دقيقة بسبب تكرار المحاولات الفاشلة"});\n  }\n  const user = db.prepare(`SELECT * FROM users WHERE username=? AND is_active=1`).get(normalized);\n  if (!user || hashPassword(password || "", user.salt) !== user.password_hash) {\n    db.prepare(`INSERT INTO login_attempts (username,success,ip_address) VALUES (?,0,?)`).run(normalized,ip);\n    audit(null,"LOGIN_FAILED","user",normalized,`Failed login from ${ip}`);\n    return res.status(401).json({ok:false,message:"بيانات الدخول غير صحيحة"});\n  }\n  db.prepare(`INSERT INTO login_attempts (username,success,ip_address) VALUES (?,1,?)`).run(normalized,ip);\n  db.prepare(`DELETE FROM login_attempts WHERE username=? AND success=0`).run(normalized);\n  const token = crypto.randomBytes(32).toString("hex");\n  const expires = new Date(Date.now() + 7*24*60*60*1000).toISOString();\n  db.prepare(`INSERT INTO sessions (user_id,token_hash,expires_at) VALUES (?,?,?)`).run(user.id, tokenHash(token), expires);\n  res.setHeader("Set-Cookie", `minya_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${process.env.RAILWAY_ENVIRONMENT ? "; Secure" : ""}`);\n  audit(user, "LOGIN", "user", user.id, `Login from ${ip}`);\n  res.json({ ok:true,user:{ id:user.id,username:user.username,display_name:user.display_name,role:user.role } });\n});\n'''
s=s[:start]+new_login+s[end:]

# Add security/session APIs before reports endpoint.
anchor2='''app.get("/api/reports", requireAuth, (req, res) => {'''
security_api='''app.get("/api/security/sessions", requireRole("admin"), (req,res)=>{\n  db.prepare(`DELETE FROM sessions WHERE expires_at < ?`).run(new Date().toISOString());\n  const sessions=db.prepare(`SELECT s.id,s.user_id,s.expires_at,s.created_at,u.username,u.display_name,u.role FROM sessions s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC`).all();\n  const users=db.prepare(`SELECT u.id,u.username,u.display_name,u.role,u.is_active,\n    (SELECT MAX(created_at) FROM login_attempts la WHERE la.username=u.username AND la.success=1) AS last_success_login,\n    (SELECT MAX(created_at) FROM login_attempts la WHERE la.username=u.username AND la.success=0) AS last_failed_login,\n    (SELECT COUNT(*) FROM sessions s WHERE s.user_id=u.id AND s.expires_at>=?) AS active_sessions\n    FROM users u ORDER BY u.id`).all(new Date().toISOString());\n  res.json({ok:true,sessions,users});\n});\napp.delete("/api/security/sessions/:id", requireRole("admin"), (req,res)=>{\n  const id=Number(req.params.id);\n  const row=db.prepare(`SELECT s.id,s.user_id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=?`).get(id);\n  if(!row) return res.status(404).json({ok:false,message:"الجلسة غير موجودة"});\n  db.prepare(`DELETE FROM sessions WHERE id=?`).run(id);\n  audit(req.user,"REVOKE_SESSION","user",row.user_id,row.username);\n  res.json({ok:true});\n});\napp.post("/api/security/users/:id/logout-all", requireRole("admin"), (req,res)=>{\n  const id=Number(req.params.id); const user=db.prepare(`SELECT id,username FROM users WHERE id=?`).get(id);\n  if(!user) return res.status(404).json({ok:false,message:"المستخدم غير موجود"});\n  const result=db.prepare(`DELETE FROM sessions WHERE user_id=?`).run(id);\n  audit(req.user,"LOGOUT_ALL_SESSIONS","user",id,`${user.username}: ${result.changes} sessions`);\n  res.json({ok:true,count:result.changes});\n});\napp.post("/api/security/cleanup", requireRole("admin"), (req,res)=>{\n  const sessions=db.prepare(`DELETE FROM sessions WHERE expires_at < ?`).run(new Date().toISOString()).changes;\n  const attempts=db.prepare(`DELETE FROM login_attempts WHERE created_at < ?`).run(new Date(Date.now()-30*24*60*60*1000).toISOString()).changes;\n  audit(req.user,"SECURITY_CLEANUP","system","security",`${sessions} sessions, ${attempts} login attempts`);\n  res.json({ok:true,sessions_removed:sessions,attempts_removed:attempts});\n});\n\n'''+anchor2
if '/api/security/sessions' not in s:
    assert anchor2 in s, 'reports anchor not found'
    s=s.replace(anchor2,security_api,1)

p.write_text(s)
