module.exports=function installIncidentFiles(app,{db,requireAuth,requireRole,audit}){
  db.exec(`CREATE TABLE IF NOT EXISTS incident_files(id INTEGER PRIMARY KEY AUTOINCREMENT,incident_id INTEGER NOT NULL,file_name TEXT NOT NULL,mime_type TEXT DEFAULT 'application/octet-stream',size_bytes INTEGER DEFAULT 0,data BLOB NOT NULL,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(incident_id) REFERENCES incident_logs(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_incident_files_incident ON incident_files(incident_id);`);
  const safeName=v=>String(v||'مرفق').replace(/[\\/\0]/g,'_').slice(0,180);
  const mimeOk=v=>/^[a-zA-Z0-9!#$&^_.+-]+\/[a-zA-Z0-9!#$&^_.+-]+$/.test(String(v||''));
  function decode(value){const text=String(value||'').replace(/^data:[^;]+;base64,/,'').trim();if(!text||text.length%4!==0||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))return null;try{return Buffer.from(text,'base64')}catch{return null}}
  app.get('/api/incidents/:id/files',requireAuth,(req,res)=>{const id=Number(req.params.id);if(!db.prepare('SELECT id FROM incident_logs WHERE id=?').get(id))return res.status(404).json({ok:false,message:'السجل غير موجود'});const files=db.prepare('SELECT id,incident_id,file_name,mime_type,size_bytes,created_at FROM incident_files WHERE incident_id=? ORDER BY id DESC').all(id);res.json({ok:true,files})});
  app.post('/api/incidents/:id/files',requireRole('admin','editor'),(req,res)=>{const incidentId=Number(req.params.id);if(!db.prepare('SELECT id FROM incident_logs WHERE id=?').get(incidentId))return res.status(404).json({ok:false,message:'السجل غير موجود'});const name=safeName(req.body?.name),mime=String(req.body?.mime_type||'application/octet-stream').slice(0,120);if(!mimeOk(mime))return res.status(400).json({ok:false,message:'نوع الملف غير صالح'});const buffer=decode(req.body?.data_base64);if(!buffer)return res.status(400).json({ok:false,message:'بيانات الملف غير صالحة'});if(buffer.length>5*1024*1024)return res.status(413).json({ok:false,message:'الحد الأقصى للمرفق 5MB'});const r=db.prepare('INSERT INTO incident_files(incident_id,file_name,mime_type,size_bytes,data,created_by) VALUES(?,?,?,?,?,?)').run(incidentId,name,mime,buffer.length,buffer,req.user.id);audit(req.user,'ADD_INCIDENT_FILE','incident',incidentId,name);res.json({ok:true,id:r.lastInsertRowid})});
  app.get('/api/incident-files/:id',requireAuth,(req,res)=>{const f=db.prepare('SELECT * FROM incident_files WHERE id=?').get(Number(req.params.id));if(!f)return res.status(404).end();res.type(f.mime_type||'application/octet-stream');res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(f.file_name)}`);res.send(f.data)});
  app.delete('/api/incident-files/:id',requireRole('admin','editor'),(req,res)=>{const id=Number(req.params.id),f=db.prepare('SELECT incident_id,file_name FROM incident_files WHERE id=?').get(id);if(!f)return res.status(404).json({ok:false,message:'المرفق غير موجود'});db.prepare('DELETE FROM incident_files WHERE id=?').run(id);audit(req.user,'DELETE_INCIDENT_FILE','incident',f.incident_id,f.file_name);res.json({ok:true})});
};